name: Jekyll Bulma
description: "Jekyll Bulma Theme, Bulma.io CSS Framework Jekyll Template for Developers"
baseurl: ""
permalink: pretty
sass:
  style: compressed
paginate: 5
paginate_path: "/blog/page:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll-bower

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor

defaults:
- scope:
    path: "assets/img"
  values:
    image: true